

binary_words = set(['is', 'are', 'was', 'were', "'s", "'re", "'ll", "will",
                    "could", "would", "may", "might", "can", "must",
                    'has', 'have', 'not', 'no', 'nor', "'t", 'wont'])

nclasses = {'ag': 4, 'yelp': 2, 'yahoo': 10, 'dbpedia': 14, 'ag_3': 4,
            'sst-2': 2, 'mnli':3, 'qnli': 2,
            'qqp': 2, 'rte': 2, 'mrpc': 2,}
class_names = {'ag': {0: 'World', 1: 'Sports', 2: 'Business', 3: 'Sci-Tech'},
               'yelp': {0: "Negative", 1: 'Positive'},
               'dbpedia': {0: 'Company', 1: 'EducationInstitution', 2: "Artist",
                           3: "Athlete", 4: "OfficeHolder", 5: "MeanOfTransportation",
                           6: "Building", 7: "NaturalPlace", 8: "Village", 9: "Animal",
                           10: "Plant", 11: "Album", 12: "Film", 13: "WrittenWork"},
               'sst-2': {0: "Negative", 1: 'Positive'},
               'mnli': {0: "Contradiction", 1: 'Entailment', 2: "Neutral"},
               'qnli': {0: "Entailment", 1: 'Not_Entailment'}, # attack_second
               'qqp': {0: "Not_Duplicate", 1: 'Duplicate'},
               'rte': {0: "Entailment", 1: 'Not_Entailment'},
               'mrpc': {0: "Paraphrase", 1: 'Not_Paraphrase'}, 
}

thres = {'ag': {'replace_prob': 0.0005, 'insert_prob': 0.0, 'merge_prob': 0.005,
                'replace_sim': 0.6, 'insert_sim': -1.0, 'merge_sim': 0.7,
                'prob_diff': -5e-4,
                'sim_window': 15},
       #   'ag': {'replace_prob': 0.0005, 'insert_prob': 0.0, 'merge_prob': 0.005,
       #          'replace_sim': 0.7, 'insert_sim': 0.0, 'merge_sim': 0.7,
       #          'prob_diff': -1e-4,
       #          'sim_window': 15},
         'dbpedia': {'replace_prob': 0.0005, 'insert_prob': 0.0, 'merge_prob': 0.005,
                     'replace_sim': 0.6, 'insert_sim': -1.0, 'merge_sim': 0.7,
                     'prob_diff': -1e-5,
                     'sim_window': 15},
         'yelp': {'replace_prob': 0.0005, 'insert_prob': 0.0, 'merge_prob': 0.005,
                  'replace_sim': 0.7, 'insert_sim': 0.7, 'merge_sim': 0.7,
                  'prob_diff': -1e-6, 'filter_adj': True, 'keep_sim': True,
                  'sim_window': 15},
         'sst-2': {'replace_prob': 0.0005, 'insert_prob': 0.0, 'merge_prob': 0.005,
                   'replace_sim': 0.6, 'insert_sim': 0.6, 'merge_sim': 0.6,
                   'prob_diff': -1e-5, 'filter_adj': True, 'keep_sim': True,
                   'sim_window': 15},
         'mnli': {'replace_prob': 0.0005, 'insert_prob': 0.0, 'merge_prob': 0.005,
                   'replace_sim': 0.7, 'insert_sim': 0.7, 'merge_sim': 0.7,
                   'prob_diff': -1e-6, 'keep_sim': True,
                   'sim_window': 15},
         'qnli': {'replace_prob': 0.0005, 'insert_prob': 0.0, 'merge_prob': 0.005,
                   'replace_sim': 0.7, 'insert_sim': 0.7, 'merge_sim': 0.7,
                   'prob_diff': -1e-6, 'keep_sim': True,
                   'sim_window': 15},
         'qqp': {'replace_prob': 0.0005, 'insert_prob': 0.0, 'merge_prob': 0.005,
                   'replace_sim': 0.7, 'insert_sim': 0.7, 'merge_sim': 0.7,
                   'prob_diff': -1e-4, 'keep_sim': True,
                   'sim_window': 15},
         'rte': {'replace_prob': 0.0005, 'insert_prob': 0.0, 'merge_prob': 0.005,
                   'replace_sim': 0.7, 'insert_sim': 0.7, 'merge_sim': 0.7,
                   'prob_diff': -1e-6, 'keep_sim': True,
                   'sim_window': 15},
         'mrpc': {'replace_prob': 0.0005, 'insert_prob': 0.0, 'merge_prob': 0.005,
                   'replace_sim': 0.7, 'insert_sim': 0.7, 'merge_sim': 0.7,
                   'prob_diff': -1e-2, 'keep_sim': True,
                   'sim_window': 15},
         }

pos_tag_filter = {
                    'replace': set(['NOUN', 'VERB', 'ADJ', 'X', 'NUM', 'ADV']),
                    'insert': set(['NOUN/NOUN', 'ADJ/NOUN', 'NOUN/VERB', 'NOUN/ADP',
                               'ADP/NOUN', 'NOUN/.', 'VERB/NOUN', 'DET/NOUN',
                               'VERB/ADJ', './NOUN', 'VERB/VERB', 'VERB/DET',
                               'DET/ADJ', 'ADJ/ADJ', 'VERB/ADP', 'NOUN/CONJ',
                               'NOUN/ADJ', 'PRT/VERB', 'ADP/DET', 'ADP/ADJ',
                               'PRON/NOUN', 'VERB/PRON', './X', './DET']),
                    'merge': set(['NOUN/NOUN', 'ADJ/NOUN', 'VERB/ADJ', 'VERB/NOUN',
                              'VERB/VERB', 'NOUN/VERB', 'DET/ADJ', 'ADJ/ADJ',
                              'DET/NOUN', 'NUM/NOUN', 'PRON/NOUN', 'NOUN/ADJ',
                              'ADV/VERB', 'VERB/ADV', 'PRON/ADJ'])
                 }

